apiVersion: v1
kind: PersistentVolume
metadata:
  name: zc-pvc
spec:
  capacity:
    storage: 1Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data
    server: 10.21.230.170
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: zc-pvc
  resources:
    requests:
      storage: 1Ti
